// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SeguridadInformatica.Data;

#nullable disable

namespace SeguridadInformatica.Migrations
{
    [DbContext(typeof(SeguridadInformaticaContext))]
    partial class SeguridadInformaticaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SeguridadInformatica.Models.Activos", b =>
                {
                    b.Property<int>("ActivosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActivosId"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Valor")
                        .HasColumnType("int");

                    b.HasKey("ActivosId");

                    b.ToTable("Activos");
                });

            modelBuilder.Entity("SeguridadInformatica.Models.Dimensiones", b =>
                {
                    b.Property<int>("DimesionesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DimesionesId"), 1L, 1);

                    b.Property<int>("ActivosId")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Valor")
                        .HasColumnType("int");

                    b.HasKey("DimesionesId");

                    b.HasIndex("ActivosId");

                    b.ToTable("Dimensiones");
                });

            modelBuilder.Entity("SeguridadInformatica.Models.Dimensiones", b =>
                {
                    b.HasOne("SeguridadInformatica.Models.Activos", "Activos")
                        .WithMany()
                        .HasForeignKey("ActivosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activos");
                });
#pragma warning restore 612, 618
        }
    }
}
